"""
Django settings for the_woman project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from django.utils.text import slugify
import certifi
import logging


# Разрешение использования русских символов в slug
def slugify_russian(value):
    return slugify(value, allow_unicode=True)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Уровень отладки
            'class': 'logging.FileHandler',
            'filename': 'log/logging.log',  # Укажите путь к файлу журнала
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'DEBUG',
    },
}



# Настройка slugify функции для использования в полях модели
SLUGIFY_FUNCTION = 'path.to.slugify_russian'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-75at2z-u)+sop$e&^pdje-kh)a(hcc((7yu*^wy=ob+6c!8tck'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['optombelie.ru', 'thewoman.balayi3c.beget.tech']

# # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.mail.ru'
# #EMAIL_PORT = 2525
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'xzibitum0527@gmail.com'
# #EMAIL_HOST_PASSWORD = 'PAnwAVUB1ej8xCxhbgrC'
# EMAIL_HOST_PASSWORD = 'kkzi mybr afcz lxrc'
# #EMAIL_HOST_PASSWORD = 'ugntypllbwthmwjz'
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# SERVER_EMAIL = EMAIL_HOST_USER
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# EMAIL_SSL_CERTFILE = certifi.where()
# #EMAIL_SSL_CERTFILE = "venv/lib/python3.11/site-packages/certifi/key.pem"
# EMAIL_SSL_CA_BUNDLE = "/home/b/balayi3c/thewoman.balayi3c.beget.tech/venv/lib/python3.11/site-packages/certifi/aukey.pem"
# EMAIL_TIMEOUT = 10
# EMAIL_USE_LOCALTIME = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use the database for session storage
SESSION_SAVE_EVERY_REQUEST = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

ROOT_URLCONF = 'the_woman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'catalog.context_processors.cart_items',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'the_woman.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'default-db',
        'USER': 'default-db',
        #'PASSWORD': 'N8cq%13YLh3L',
        #'PASSWORD': 'h04fHgy6zc7%',
        'PASSWORD': 'rw%%y*J5ys8x',
        #'HOST': 'bipipikub.beget.app',  # Измените настройки под свой сервер MySQL
        #'HOST': 'gitotuertel.beget.app',
        'HOST': 'quoraquofa.beget.app',
        'PORT': '3306',       # Измените настройки под свой сервер MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_ALL_TABLES'"
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'public_html/static/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    MEDIA_ROOT,
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
