# Generated by Django 4.2.1 on 2023-11-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_size_65',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (1-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AddField(
            model_name='product',
            name='num_of_size_xxl',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (6-я ячейка/нижняя часть комплекта)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_65',
            field=models.CharField(default='65', max_length=15, verbose_name='Название размера в первой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xxl',
            field=models.CharField(blank=True, default='XXL', max_length=15, verbose_name='Название размера в шестой ячейке (нижняя часть комплекта)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_70',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (2-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_75',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (3-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_80',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (4-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_85',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (5-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_90',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (6-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_70',
            field=models.CharField(default='70', max_length=15, verbose_name='Название размера во второй ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_75',
            field=models.CharField(blank=True, default='75', max_length=15, verbose_name='Название размера в третьей ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_80',
            field=models.CharField(blank=True, default='80', max_length=15, verbose_name='Название размера в четвертой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_85',
            field=models.CharField(blank=True, default='85', max_length=15, verbose_name='Название размера в пятой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_90',
            field=models.CharField(blank=True, default='90', max_length=15, verbose_name='Название размера в шестой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
    ]
