# Generated by Django 4.2.1 on 2023-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_num_of_size_65_product_num_of_size_xxl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_of_size_65',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_of_size_xxl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_65',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_xxl',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Белый', 'White'), ('Бело-красный', 'White-Red'), ('Бело-розовый', 'White-Rose'), ('Бордовый', 'Vinous'), ('Голубой', 'Blue-W'), ('Капучино', 'Coffee'), ('Красный', 'Red'), ('Леопард', 'Leopard'), ('Молочный', 'Milk'), ('Розовый', 'Rose'), ('Синий', 'Blue'), ('Черный', 'Black'), ('Шампань', 'Champagne'), ('Черно-розовый', 'Black-and-Pink'), ('Черно-красный', 'Black-and-Red'), ('Черно-золотой', 'Black-and-Gold'), ('Черно-белый', 'Black-and-White'), ('Черно-бежевый', 'Black-and-Beige'), ('Фуксия', 'Fuchsia'), ('Фиолетовый', 'Purple'), ('Темно-зеленый', 'Dark-Green'), ('Телесный', 'Flesh'), ('Слива', 'Plum'), ('Сине-бежевый', 'Blue-and-Beige'), ('Серый', 'Gray'), ('Салатовый', 'Salad'), ('Розы', 'Rose-flowers'), ('Пудра', 'Powder'), ('Персик', 'Peach'), ('Пенка', 'Foam'), ('Оранжевый', 'Orange'), ('Оливковый', 'Olive'), ('Нефрит', 'Jade'), ('Мята', 'Mint'), ('Красно-бежевый', 'Red-and-Beige'), ('Кофе', 'Coffee-ex'), ('Изумрудный', 'Emerald'), ('Желтый', 'Yellow'), ('Джинсовый', 'Denim'), ('Бордово-бежевый', 'Burgundy-beige'), ('Бело-бежевый', 'White-and-beige'), ('Бежевый', 'Beige'), ('Бежево-розовый', 'Beige-and-Rose'), ('Пастель', 'Pastel'), ('Принт', 'Print'), ('Терракот', 'Terracot'), ('Хаки', 'Khaki'), ('Темно-серый', 'Dark-gray'), ('Графит', 'Graphite'), ('Принт кофе', 'Print-coffee'), ('Принт зеленый', 'Pring-green'), ('Серо-белый', 'Gray-white'), ('Бежевый леопард', 'Beige-leopard'), ('Серый леопард', 'Gray-leopard'), ('Карамель', 'Caramel'), ('Стразы', 'Srtaz'), ('Сердца', 'Hearts'), ('Дождь', 'Rain'), ('Крылья', 'Wings'), ('Корона', 'Crown'), ('Алмаз', 'Diamond'), ('Пчела', 'Bee'), ('Глаз', 'Eye'), ('Стрекоза', 'Dragonfly'), ('Очки', 'Glasses'), ('Бирюзовый', 'Turquoise'), ('Ярко-розовый', 'Bright-pink'), ('Бежево-фисташковый', 'Beige-pistachio')], default='Черный', max_length=50, verbose_name='Выберите основной цвет товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_70',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (1-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_75',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (2-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_80',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (3-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_85',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (4-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_size_90',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в упаковке (5-я ячейка/вехняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_70',
            field=models.CharField(default='70', max_length=15, verbose_name='Название размера в первой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_75',
            field=models.CharField(blank=True, default='75', max_length=15, verbose_name='Название размера во второй ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_80',
            field=models.CharField(blank=True, default='80', max_length=15, verbose_name='Название размера в третьй ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_85',
            field=models.CharField(blank=True, default='85', max_length=15, verbose_name='Название размера в четвертой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_90',
            field=models.CharField(blank=True, default='90', max_length=15, verbose_name='Название размера в пятой ячейке (верхняя часть комплекта или, если не комплект, то просто размер одежды)'),
        ),
    ]
